Repository eslint/generator-eslint, pull requests merged in 2022-07, with the labels that each got.

#129 chore: recreate package-lock.json
  app/index.js
  package-lock.json
  plugin/index.js
  tests/app/index.js
  tests/lib/validators.js
  tests/plugin/index.js
  tests/rule/index.js
  tests/test-load.js
Labels: chore

#127 ci: update github actions
  .github/workflows/ci.yml
Labels: accepted, chore, build

#130 ci: add node v18 to test workflow
  .github/workflows/ci.yml
Labels: triage, build

#132 fix: remove unused meta.docs.category field in rule template
  rule/templates/_rule.js
Labels: bug, triage

#128 chore: add funding field
  package.json
Labels: triage, chore

#136 feat: drop ESLint v6 support in plugin template
  plugin/templates/_package.json
Labels: triage, feature

#134 feat: strictly define Node API in plugin template
  plugin/templates/_package.json
Labels: accepted, feature

#135 feat!: drop Node 12/17 support
  .github/workflows/ci.yml
  package-lock.json
  package.json
  plugin/templates/_package.json
Labels: triage, breaking, feature

#133 feat: upgrade plugin template dependencies
  plugin/templates/_package.json
Labels: triage, feature

#138 chore: update all dependencies
  package-lock.json
  package.json
Labels: triage, chore
