Repository eslint/generator-eslint, pull requests merged in 2023-04, with the labels that each got.

#152 chore: Also post releases to Mastodon
  .github/workflows/release-please.yml
Labels: chore

#153 ci: run tests on Node.js v20
  .github/workflows/ci.yml
Labels: build

#154 chore: include all commits in the changelog
  .github/workflows/release-please.yml
Labels: accepted, chore
