Repository eslint/generator-eslint, pull requests merged in 2023-10, with the labels that each got.

#165 chore: Update add-to-triage.yml
  .github/workflows/add-to-triage.yml
Labels: chore

#168 ci: don't install latest npm
  .github/workflows/ci.yml
Labels: build

#167 ci: run tests in Node.js 21
  .github/workflows/ci.yml
Labels: build

#164 feat: add auto-generated configs list to readme in template
  plugin/templates/_README.md
Labels: feature
