Repository eslint/generator-eslint, pull requests merged in 2024-05, with the labels that each got.

#182 feat: add messages to rule template
  rule/templates/_rule.js
Labels: feature

#183 docs: align readme node.js with package.json
  README.md
Labels: documentation

#184 ci: reduce list of releasable tags to `feat`, `fix` and `perf`
  .github/workflows/release-please.yml
Labels: accepted, build

#179 feat: update templates for eslint v9
  .eslintignore
  .eslintrc.cjs
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  .npmrc
  app/index.js
  eslint.config.js
  package-lock.json
  package.json
  plugin/index.js
  plugin/templates/_.eslintrc.js
  plugin/templates/_eslint.config.mjs
  plugin/templates/_package.json
  rule/index.js
  tests/app/index.js
  tests/plugin/index.js
  tests/rule/index.js
  tests/test-load.js
Labels: feature

#187 ci: Test in Node.js 22
  .github/workflows/ci.yml
Labels: accepted, build

#186 chore: add `.vscode` to `.gitignore`
  .gitignore
Labels: accepted, chore

#190 feat: add `"files"` to generated `package.json`
  plugin/templates/_package.json
Labels: evaluating, feature

#189 feat: use `messageId` in tests
  rule/templates/_test.js
Labels: evaluating, feature
