Repository eslint/generator-eslint, pull requests merged in 2025-09, with the labels that each got.

#211 chore: update eslint-config-eslint
  package.json
Labels: chore

#218 test: adopt `.test` suffix for test files
  eslint.config.js
  package.json
  tests/app/index.test.js
  tests/lib/validators.test.js
  tests/plugin/index.test.js
  tests/rule/index.test.js
  tests/test-load.test.js
Labels: accepted, chore

#223 ci: workaround for a flaky test in Node.js 18.18.0
  .github/workflows/ci.yml
Labels: chore, build

#225 ci: create `update-readme` workflow
  .github/workflows/update-readme.yml
  .gitignore
  README.md
Labels: accepted, build
